1904-gs-rr/graceshopper

team_expectations.md
---
I'm making notes here as an experiment
=> added team expectations markdown

team_expectations.md
---
I added this to test out pulling and pushing
=> added my name (dbtracy)

team_expectations.md
=> added jorge name

README.md
=> jorge name added

team_expectations.md
=> added wilson

server/db/models/cart.js, server/db/models/index.js, server/db/models/product.js
* [ x] add sequelize models
We added a product and cart model. We made associations between user and cart and product and cart.
=> added sequelize models

server/api/index.js, server/api/products.js, server/api/users.js
Created some product and user API routes
=> Express routes

package-lock.json, script/seed.js
seeded the products, seeded the users, seeded the cart
=> finished seed file

package-lock.json, server/api/users.js
=> user login first commit

client/components/all-products.js, client/components/index.js, client/components/navbar.js, client/components/single-product.js, client/routes.js, client/store/index.js, client/store/products.js, public/index.html, server/api/products.js
We added an all products and single product component, and we edited the store to include the products
=> added components, edited store

client/components/cart.js, client/components/navbar.js, client/routes.js, client/store/cart.js, client/store/index.js, script/seed.js, server/api/cart.js, server/api/index.js, server/api/users.js, server/auth/index.js
---
Added route and component for display cart
=> display cart route and component

client/store/cart.js, server/api/cart.js
added to store and API/cart so that users can add to cart (back-end only)
=> add to cart

client/store/cart.js
=> added single curly brace on cart

client/components/all-products.js, client/store/cart.js, server/api/cart.js, server/auth/index.js
=> Guest checkout2

script/seed.js, server/api/index.js, server/api/order.js, server/api/users.js, server/auth/index.js, server/db/models/index.js, server/db/models/order.js, server/db/models/product.js
Check out our API routes and our DB schema. Cart is now Order. An unfulfilled order is the 'cart' and other orders will be part of the order history. IMPORTANT: we must be able to change status of order to fulfilled after checkout.
=> Fixing schema

client/components/single-product.js, server/auth/index.js
We can now add a product to cart on the single product view only for logged in users.
=> added add to cart button functionality on single product view

package-lock.json, package.json, server/db/models/product.js, server/db/models/product.spec.js, server/db/models/user.spec.js
* [x ] added unit tests (or none needed)
Added several tests including ones checking: product model db, validation, user model db validation, and user / order association
=> added model tests

client/components/all-products.js, client/store/user.js, server/api/order.js
We added functionality to the Add Product button so a user can add to cart. Also, user carts no longer persist after logout.
=> Add to cart functionality

client/components/cart.js, server/api/order.js
=> fixed guest cart render

server/api/order.js, server/api/useless_cart.js, server/db/models/index.js
-add to cart, will now increment quantity in through table if item is already in users cart.
=> added quantity to through table

client/components/all-products.js, client/components/cart.js, client/components/single-product.js
=> Cart functionality

server/api/checkout.js, server/api/index.js, server/api/order.js, server/auth/index.js
feat(api/checkout) - decrements product quantity upon checkout in database, gives user a new card, changes order status from false to true
=> finished checkout backend

client/components/single-product.js, client/store/cart.js, server/api/order.js
edited back end routes so that we can now add multiple items to a cart via drop-down menu
=> FEAT:back end routes for adding multiple items to cart

.travis.yml
fix(travis.yml): added heroku-token
=> changed travis file

client/components/all-products.js
=> commented out all-products add product button and quantity

client/components/checkout.js, client/routes.js
=> feature:checkout

client/components/cart.js, client/components/checkout.js
=> Guest cart checkout prep

client/components/checkout.js
=> cart checkout works again

client/components/all-products.js, package-lock.json, package.json, public/index.html, script/seed.js
added bootstrap. Make sure to npm install bootstrap on your machine
=> FEATURE(index.html): added bootstrap

server/api/users.js
-Logged in users can no longer make get request for other users
=> added backend security

public/google7dcf8f5d068b96e9.html
=> oAuth domain verification for heroku

server/api/admin.js, server/api/index.js, server/api/order.js
Feature: admin page
Added some routes for updating users and products. Still needs work
=> started work on admin routes

server/api/payment.js, server/api/stripe.js
-added stripe front end component
-added stripe back end route to accept payments
=> finished stripe

client/components/auth-form.js, client/store/user.js, package-lock.json, server/api/order.js, server/api/users.spec.js
=> FIX(guest cart transfer): commented out route

.travis.yml, server/auth/google.js
=> added secret
